// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDybjGm9e_wxDWjGQLzr3TT-lN00MFqRBI',
    appId: '1:567799613562:web:0a843c0e4f777bd0db53c3',
    messagingSenderId: '567799613562',
    projectId: 'pos-restra',
    authDomain: 'pos-restra.firebaseapp.com',
    storageBucket: 'pos-restra.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_BZ4bqPROtTw8A4cMiK21EbE6rgrivFk',
    appId: '1:567799613562:android:ee8dbd0e476421b7db53c3',
    messagingSenderId: '567799613562',
    projectId: 'pos-restra',
    storageBucket: 'pos-restra.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYnKaqUkO5MigSA9XPMvSK_1eqXublXME',
    appId: '1:567799613562:ios:c58013617c6f2c08db53c3',
    messagingSenderId: '567799613562',
    projectId: 'pos-restra',
    storageBucket: 'pos-restra.appspot.com',
    iosClientId: '567799613562-8707s4i805nkdqqovovc6agc6fd8eaa8.apps.googleusercontent.com',
    iosBundleId: 'com.example.pos',
  );
}
